stages:
  - Artifacts
  - Cross-Project
  - End-to-End
  - Dashboard-Update

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
  - export CI_COMMIT_SHA_SHORT=$(echo ${CI_COMMIT_SHA} | cut -c -8)
  - mkdir -p ./data ; touch ./data/empty.env
  - for envfile in data/*env ; do source $envfile ; echo ----- $envfile ---- ; cat $envfile ; done
  - >
    if [ -z "$CROSS_CLOUD_YML" ]; then
      export CROSS_CLOUD_YML="https://raw.githubusercontent.com/CrossCloudCI/cncf-configuration/production/cross-cloud.yml"
    else
      export CROSS_CLOUD_YML="$CROSS_CLOUD_YML"
    fi
  - source /opt/local/etc/rvmrc ; source /opt/local/etc/profile.d/rvm.sh ; cp -a /opt/local/dashboard /dashboard ; pushd /dashboard ; source /opt/local/.env ; ./bin/update_dashboard ; popd


.build_source: &build_source
  image: buildpack-deps:stretch
  stage: Artifacts
  variables:
    # SOURCE
    # ORG: MUST BE SET
    # PROJECT: MUST BE SET
    # PROJECT_ID: MUST BE SET
  script:
    - apt update && apt -y install jq
    - >
      if [ -z "${SOURCE}" ]; then
        exit 0 #Should Show Skipped on Gitlab CI FIXME
      elif [ "${DISABLE_SOURCE}" == "yes" ]; then
        exit 0 #Should Show Skipped on Gitlab CI FIXME
      else
        PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "${BASE_URL}/api/v4/projects/$PROJECT_ID/pipelines/${SOURCE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .id') 
        curl -s -o data/"$TARGET_PROJECT_NAME".env -L "${BASE_URL}/${ORG}/${TARGET_PROJECT_NAME}/-/jobs/${PROJECT_JOB}/artifacts/raw/release.env"
        cat data/"$TARGET_PROJECT_NAME".env
      fi

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 5 weeks
    paths:
      - ./data

.cross-project: &cross-project
  #image: registry.cncf.ci/cncf/cross-cloud/provisioning:production
  image: crosscloudci/debian-helm-kubectl:v2.7.2-v1.7.12
  stage: Cross-Project
  # variables:
    # KUBECONFIG: MUST BE SET
    # CLOUD: MUST BE SET
  script:
    #- helm init || true
    #- pushd $(pwd)/charts ; make all ; popd
    #- helm repo list
    - echo "$KUBECONFIG" | base64 -d | tee ./kubeconfig
    - export KUBECONFIG=./kubeconfig
    - kubectl get nodes
    - kubectl get componentstatuses
    - env | grep IMAGE
    - env | grep TAG
    - helm init
    - echo Removing any previous deploys of "${DEPLOYMENT_NAME}"
    - helm ls --all "${DEPLOYMENT_NAME}" > /dev/null && helm delete --purge "${DEPLOYMENT_NAME}" || true
    - helm repo add cncf http://cncf.gitlab.io/stable
    - helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
    - helm repo add onap-amsterdam  http://cncf.gitlab.io/onap-amsterdam
    - helm repo add onap-master  http://cncf.gitlab.io/onap-master 
    - >
      if [ "$TARGET_PROJECT_NAME" == so ]; then

         echo "Remove old deploys"
         helm delete --purge onap-config || true
         helm delete --purge onap-log || true
         helm delete --purge onap-robot || true
         kubectl delete namespace onap || true
         kubectl delete namespace onap-log || true
         kubectl delete namespace onap-mso || true
         kubectl delete namespace onap-robot || true
         kubectl delete clusterrolebinding onap-config-admin-binding || true
         kubectl delete clusterrolebinding onap-log-admin-binding || true
         kubectl delete clusterrolebinding onap-mso-admin-binding || true
         kubectl delete clusterrolebinding onap-robot-admin-binding || true
         sleep 10

         echo "Create project namespaces"
         kubectl create namespace onap
         kubectl create namespace onap-log
         kubectl create namespace onap-mso
         kubectl create namespace onap-robot

         echo "Adding onap secret to cluster"
         kubectl create secret docker-registry onap-docker-registry-key --docker-server=nexus3.onap.org:10001 --docker-username="$ONAP_USERNAME" --docker-password="$ONAP_PASSWORD" --docker-email="$ONAP_EMAIL" --namespace=onap
         kubectl create secret docker-registry onap-docker-registry-key --docker-server=nexus3.onap.org:10001 --docker-username="$ONAP_USERNAME" --docker-password="$ONAP_PASSWORD" --docker-email="$ONAP_EMAIL" --namespace=onap-log
         kubectl create secret docker-registry onap-docker-registry-key --docker-server=nexus3.onap.org:10001 --docker-username="$ONAP_USERNAME" --docker-password="$ONAP_PASSWORD" --docker-email="$ONAP_EMAIL" --namespace=onap-mso
         kubectl create secret docker-registry onap-docker-registry-key --docker-server=nexus3.onap.org:10001 --docker-username="$ONAP_USERNAME" --docker-password="$ONAP_PASSWORD" --docker-email="$ONAP_EMAIL" --namespace=onap-robot
         
         echo "Add clusterrolebinding"
         kubectl create clusterrolebinding onap-config-admin-binding --clusterrole=cluster-admin --serviceaccount=onap:default
         kubectl create clusterrolebinding onap-log-admin-binding --clusterrole=cluster-admin --serviceaccount=onap-log:default
         kubectl create clusterrolebinding onap-mso-admin-binding --clusterrole=cluster-admin --serviceaccount=onap-mso:default
         kubectl create clusterrolebinding onap-robot-admin-binding --clusterrole=cluster-admin --serviceaccount=onap-robot:default
         
         echo "Create Config/Log/Robot"
         helm install --name onap-config --namespace=onap onap-amsterdam/config
         helm install --name onap-log --namespace=onap-log onap-amsterdam/log
         helm install --name onap-robot --namespace=onap-robot onap-amsterdam/robot
         export NAMESPACE="onap-mso"
      else
        echo "skipping onap configuration"
      fi
    - helm install -f defaults/"${TARGET_PROJECT_NAME}".yaml
         --namespace "${NAMESPACE}"
         --name "${DEPLOYMENT_NAME}"
         $IMAGE_ARGS
         $TAG_ARGS
         "${CHART_REPO}"/"${CHART}"
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 5 weeks
    paths:
      - ./data

e2e:
  image: crosscloudci/debian-helm-kubectl:v2.7.2-v1.7.12
  stage: End-to-End
  script:
    - echo "$KUBECONFIG" | base64 -d | tee ./kubeconfig
    - export KUBECONFIG=./kubeconfig
    - >
      if [ "$TARGET_PROJECT_NAME" == so ]; then
         ls -al
         ./cd.sh
      else
        echo "skipping onap configuration"
      fi


Dashboard:
  image: crosscloudci/debian-go
  stage: Dashboard-Update
  script:
    - echo 'test'


# Build-Source VARs
Build-Source:
  <<: *build_source

# Project Deploy VARs
App-Deploy:
  <<: *cross-project



